// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnl5bxa2LESrrmFi_OfvIQq9cg242J4Mk',
    appId: '1:45891953045:android:94a1cbeac67b9f47ad969c',
    messagingSenderId: '45891953045',
    projectId: 'harmoni-cb886',
    storageBucket: 'harmoni-cb886.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfm07ce9IZSHXgkT9bJ_x2SYeX5aI9gTw',
    appId: '1:45891953045:ios:a2691381ba45a3d8ad969c',
    messagingSenderId: '45891953045',
    projectId: 'harmoni-cb886',
    storageBucket: 'harmoni-cb886.firebasestorage.app',
    androidClientId: '45891953045-gp1e4qkba1a05oh0dpke9cqgfag7kgt8.apps.googleusercontent.com',
    iosClientId: '45891953045-pa0vmdc7h42t6406mt7qfiu0g7v2qr5g.apps.googleusercontent.com',
    iosBundleId: 'com.example.harmoni',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD56_SpcNA4WEuEfvue5pAMM4taLIz9MJI',
    appId: '1:45891953045:web:49be5f491a1bf359ad969c',
    messagingSenderId: '45891953045',
    projectId: 'harmoni-cb886',
    authDomain: 'harmoni-cb886.firebaseapp.com',
    storageBucket: 'harmoni-cb886.firebasestorage.app',
    measurementId: 'G-2LV5T1DW9L',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfm07ce9IZSHXgkT9bJ_x2SYeX5aI9gTw',
    appId: '1:45891953045:ios:a2691381ba45a3d8ad969c',
    messagingSenderId: '45891953045',
    projectId: 'harmoni-cb886',
    storageBucket: 'harmoni-cb886.firebasestorage.app',
    androidClientId: '45891953045-gp1e4qkba1a05oh0dpke9cqgfag7kgt8.apps.googleusercontent.com',
    iosClientId: '45891953045-pa0vmdc7h42t6406mt7qfiu0g7v2qr5g.apps.googleusercontent.com',
    iosBundleId: 'com.example.harmoni',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD56_SpcNA4WEuEfvue5pAMM4taLIz9MJI',
    appId: '1:45891953045:web:ea51b837a97fb966ad969c',
    messagingSenderId: '45891953045',
    projectId: 'harmoni-cb886',
    authDomain: 'harmoni-cb886.firebaseapp.com',
    storageBucket: 'harmoni-cb886.firebasestorage.app',
    measurementId: 'G-SY7ZNDWY5X',
  );

}